### ISSUE TITLE
Swiper强制刷新实现动态高度

### ISSUE THREAD

**Issue by yifengyoujian** [AntmJS/vantui#532]
**这个 Issue 涉及以下平台:**
Web 平台（H5）
**BUG 描述**
swiper.js:452 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at eval (swiper.js:452:1)
    at new Promise (<anonymous>)
    at eval (swiper.js:450:1)
    at eval (swiper.js:459:1)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (_async_to_generator.js:3:1)
    at _next (_async_to_generator.js:20:1)
    at eval (_async_to_generator.js:27:1)
    at new Promise (<anonymous>)
    at eval (_async_to_generator.js:16:1)
**复现步骤**
![~I_5UY8X%23N(FU R$8 9OI](https://github.com/AntmJS/vantui/assets/65208277/af749ac9-94f2-4195-9cac-8fcf0a6d0c2d)
动态获取高度, 强制刷新组件.
**期望结果**
不会报错, 或者更新height的值重新渲染.
**实际结果**
报错但是不影响使用
**截图**

**环境**
Web 平台（H5）
**附加信息**
添加resize方法重新绘制

**Comment by yifengyoujian** [comment]
微信小程序同样出现了
